"""empty message

Revision ID: dfea68351dd6
Revises: 8264c1d5ffbd
Create Date: 2024-08-31 12:00:48.741140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfea68351dd6'
down_revision: Union[str, None] = '8264c1d5ffbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('creator', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'companies', 'users', ['creator'], ['id'])
    op.add_column('tasks', sa.Column('creator', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('assignee', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['assignee'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['creator'], ['id'])
    op.add_column('users', sa.Column('company', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_foreign_key(None, 'users', 'companies', ['company'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'company')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assignee')
    op.drop_column('tasks', 'creator')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'creator')
    # ### end Alembic commands ###
